"use client";

import { useEffect, useState, useCallback } from "react";
import { useParams } from "next/navigation";
import { confidenceLabel } from "@/lib/pipeline/confidence";
import { MITRE_MAPPINGS } from "@/lib/attack/mitreMapping";
import type { InvestigationDetail, Finding, Evidence, Artifact } from "@/lib/pipeline/types";
import RadarChart from "@/components/RadarChart";

const ANALYZER_BADGES: Record<string, string> = {
  VirusTotalAnalyzer: "VT",
  AbuseIPDBAnalyzer: "ABUSE",
  DomainAgeAnalyzer: "WHOIS",
  EntropyAnalyzer: "ENT",
  ASNReputationAnalyzer: "ASN",
  HomographAnalyzer: "HOM",
  EmailAuthAnalyzer: "HDR",
  FingerprintAnalyzer: "FP",
  CVEPriorityAnalyzer: "CVE",
};

const STATUS_LABELS: Record<string, string> = {
  CREATED: "Created",
  FETCHING_ARTIFACTS: "Fetching sources…",
  EXTRACTING_EVIDENCE: "Extracting evidence…",
  RUNNING_ANALYZERS: "Running analyzers…",
  SCORING: "Computing score…",
  COMPLETED: "Completed",
  FAILED: "Failed",
};

function ScoreColor(score: number): string {
  if (score >= 75) return "var(--severity-critical)";
  if (score >= 50) return "var(--severity-high)";
  if (score >= 25) return "var(--severity-medium)";
  return "var(--severity-low)";
}

function StampBadge({ status }: { status: string }) {
  const [animated, setAnimated] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setAnimated(true), 100);
    return () => clearTimeout(t);
  }, []);

  const cls = `finding-status status-${status} ${animated ? "stamp-animate" : ""}`;
  return <span className={cls}>{status.replace("_", " ")}</span>;
}

function EvidencePanelContent({
  finding,
  artifacts,
}: {
  finding: Finding & { evidence?: Evidence[] };
  artifacts: Artifact[];
}) {
  const [showRaw, setShowRaw] = useState(false);

  const evidenceList = finding.evidence ?? [];

  // Find the artifact for the first evidence item
  const firstEvidence = evidenceList[0];
  const relatedArtifact = firstEvidence
    ? artifacts.find((a) =>
        evidenceList.some(
          (ev: Evidence) => (ev as Evidence & { artifact_id: string }).artifact_id === a.id
        )
      )
    : null;

  return (
    <div className="evidence-panel-body">
      <div className="ep-meta-row">
        <span className="text-secondary" style={{ fontSize: "0.8125rem" }}>
          Generated by{" "}
          <span className="mono" style={{ color: "var(--accent-open)" }}>
            {finding.generated_by} v{finding.analyzer_version}
          </span>
        </span>
        <span className="text-tertiary" style={{ fontSize: "0.75rem" }}>
          Score contribution:{" "}
          <span className="mono" style={{ color: ScoreColor(finding.confidence_score) }}>
            +{finding.score_contribution}
          </span>
        </span>
      </div>

      {finding.reasoning && (
        <p className="ep-reasoning">{finding.reasoning}</p>
      )}

      {evidenceList.length > 0 && (
        <div className="ep-evidence-list">
          <div className="ep-section-label">Evidence</div>
          {evidenceList.map((ev: Evidence) => (
            <div key={ev.id} className="ep-evidence-row">
              <span className="mono text-tertiary" style={{ fontSize: "0.75rem" }}>
                {ev.fact_type}
              </span>
              <span className="mono" style={{ fontSize: "0.8125rem", color: "var(--text-primary)" }}>
                {typeof ev.fact_value === "object"
                  ? JSON.stringify(ev.fact_value)
                  : String(ev.fact_value)}
              </span>
            </div>
          ))}
        </div>
      )}

      {relatedArtifact && (
        <div style={{ marginTop: "1rem" }}>
          <button
            className="btn btn-secondary"
            style={{ fontSize: "0.8125rem", padding: "6px 12px" }}
            onClick={() => setShowRaw(!showRaw)}
            id={`raw-artifact-toggle-${finding.id}`}
          >
            {showRaw ? "Hide Raw Artifact" : "View Raw Artifact →"}
          </button>
          {showRaw && (
            <pre className="raw-artifact-view">
              {JSON.stringify(relatedArtifact.raw_response, null, 2)}
            </pre>
          )}
        </div>
      )}
    </div>
  );
}

function FindingCard({
  finding,
  artifacts,
}: {
  finding: Finding & { evidence?: Evidence[] };
  artifacts: Artifact[];
}) {
  const [open, setOpen] = useState(false);
  const badge = ANALYZER_BADGES[finding.generated_by] ?? finding.generated_by.slice(0, 4).toUpperCase();
  const conf = confidenceLabel(finding.confidence_score);

  return (
    <div className="finding-card evidence-tag">
      <div
        className="finding-card-header"
        onClick={() => setOpen(!open)}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => e.key === "Enter" && setOpen(!open)}
        id={`finding-${finding.id}`}
        aria-expanded={open}
      >
        <div className="finding-card-left">
          <span
            className="analyzer-badge"
            title={finding.generated_by}
            aria-label={finding.generated_by}
          >
            {badge}
          </span>
          <span className="finding-claim">{finding.claim}</span>
        </div>
        <div className="finding-card-right">
          {finding.attack_techniques?.map((t) => (
            <a
              key={t}
              href={MITRE_MAPPINGS[t]?.url ?? `https://attack.mitre.org/techniques/${t.split('.')[0]}/`}
              target="_blank"
              rel="noreferrer"
              className="severity-badge severity-INFO"
              style={{ textDecoration: "none" }}
              onClick={(e) => e.stopPropagation()}
              title={MITRE_MAPPINGS[t]?.techniqueName}
            >
              {t}
            </a>
          ))}
          <span className={`severity-badge severity-${finding.severity}`}>
            {finding.severity}
          </span>
          <span
            className="mono"
            style={{ fontSize: "0.75rem", color: "var(--text-tertiary)" }}
          >
            {finding.confidence_score}
            <span style={{ marginLeft: "2px", opacity: 0.6 }}>({conf})</span>
          </span>
          <StampBadge status={finding.status} />
          <span style={{ color: "var(--text-tertiary)", fontSize: "0.875rem" }}>
            {open ? "▲" : "▼"}
          </span>
        </div>
      </div>

      {open && (
        <EvidencePanelContent finding={finding} artifacts={artifacts} />
      )}
    </div>
  );
}

function SourceStatusBar({
  failedSources = [],
  sources,
}: {
  failedSources?: Array<{ source: string; reason: string }>;
  sources: string[];
}) {
  const failedSet = new Set(failedSources.map((f) => f.source));
  const failedMap = Object.fromEntries(failedSources.map((f) => [f.source, f.reason]));

  return (
    <div className="source-status-bar">
      <span className="source-status-label">Sources</span>
      <div className="source-status-list">
        {sources.map((src) => {
          const failed = failedSet.has(src);
          return (
            <span
              key={src}
              className={`source-status-item ${failed ? "source-fail" : "source-ok"}`}
              title={failed ? failedMap[src] : "Success"}
            >
              {failed ? "⚠" : "✓"} {src}
            </span>
          );
        })}
      </div>
    </div>
  );
}

function EvidenceLedger({
  investigation,
}: {
  investigation: InvestigationDetail;
}) {
  const { case_number, target, findings, final_score } = investigation;
  const sorted = [...findings].sort((a, b) => b.score_contribution - a.score_contribution);

  return (
    <div style={{
      fontFamily: "var(--font-mono)",
      border: "1px dashed var(--text-tertiary)",
      padding: "1rem",
      backgroundColor: "var(--bg-base)",
      fontSize: "0.8125rem",
      lineHeight: "1.5",
      color: "var(--text-primary)"
    }}>
      {/* Header */}
      <div style={{ borderBottom: "1px dashed var(--text-tertiary)", paddingBottom: "1rem", marginBottom: "1rem" }}>
        <div style={{ fontWeight: 600, letterSpacing: "0.05em", marginBottom: "0.5rem" }}>THREAT SCORE LEDGER</div>
        <div style={{ display: "flex", justifyContent: "space-between", color: "var(--text-secondary)" }}>
          <span>CASE: {case_number}</span>
          <span>TARGET: {target}</span>
        </div>
      </div>
      
      {/* Radar Chart */}
      {findings.length > 0 && (
        <div style={{ marginBottom: "1.5rem", paddingBottom: "1rem", borderBottom: "1px dashed var(--text-tertiary)" }}>
          <RadarChart findings={findings} />
        </div>
      )}
      
      {/* Table Header */}
      <div style={{ display: "flex", justifyContent: "space-between", color: "var(--text-secondary)", marginBottom: "0.5rem" }}>
        <span>CONTRIBUTING FACTOR</span>
        <span>IMPACT</span>
      </div>
      <div style={{ borderBottom: "1px dashed var(--text-tertiary)", marginBottom: "0.5rem" }}></div>
      
      {/* Items */}
      <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem", marginBottom: "1rem" }}>
        {sorted.map(f => (
          <div key={f.id} style={{ display: "flex", justifyContent: "space-between" }}>
            <span style={{ paddingRight: "1rem", wordBreak: "break-word" }}>{f.claim}</span>
            <span style={{ 
              color: f.score_contribution > 0 ? ScoreColor(f.confidence_score) : "var(--text-tertiary)",
              whiteSpace: "nowrap",
              textAlign: "right"
            }}>
              +{f.score_contribution}
            </span>
          </div>
        ))}
      </div>
      
      {/* Footer */}
      <div style={{ borderTop: "1px dashed var(--text-tertiary)", paddingTop: "1rem" }}>
        <div style={{ display: "flex", justifyContent: "space-between", fontWeight: 600 }}>
          <span>COMPOSITE SCORE SUMMARY</span>
          <span style={{ color: final_score !== null ? ScoreColor(final_score) : "var(--text-primary)" }}>
            SCORE: {final_score ?? "—"}
          </span>
        </div>
      </div>
    </div>
  );
}

function InvestigationTimeline({
  investigation,
}: {
  investigation: InvestigationDetail;
}) {
  const artifacts = investigation.artifacts;
  const findings = investigation.findings;
  const metrics = investigation.metrics;

  const formatTime = (d?: string | null) =>
    d ? new Date(d).toLocaleTimeString("en-US", { hour12: false, hour: "2-digit", minute: "2-digit", second: "2-digit" }) : "Unknown";

  const steps = [
    {
      time: formatTime(investigation.created_at),
      label: "IOC submitted",
      detail: `Target: ${investigation.target} (${investigation.target_type})`,
      status: "completed",
    },
    ...artifacts.map((art) => {
      const artFindings = findings.filter((f) =>
        f.evidence?.some((ev: Evidence) => (ev as Evidence & { artifact_id?: string }).artifact_id === art.id)
      );
      const artEvidence = (investigation.all_evidence || []).filter(
        (ev: Evidence) => ev.artifact_id === art.id
      );
      return {
        time: formatTime(art.fetched_at || ((art as unknown) as Record<string, unknown>).created_at as string),
        label: `${art.source} artifact ${art.is_reused ? "(cached)" : "fetched"}`,
        detail: `${artEvidence.length} evidence fact${artEvidence.length !== 1 ? "s" : ""} extracted${artFindings.length > 0 ? `, ${artFindings.length} finding${artFindings.length !== 1 ? "s" : ""}` : ""}`,
        status: "completed",
      };
    }),
    ...(investigation.status === "COMPLETED" || investigation.status === "FAILED"
      ? [
          {
            time: investigation.completed_at
              ? formatTime(investigation.completed_at)
              : "",
            label: investigation.status === "COMPLETED"
              ? `Score computed under Scoring Profile v${investigation.scoring_profile_version ?? "1.0"}`
              : "Investigation failed",
            detail: investigation.status === "COMPLETED"
              ? `Final verdict: ${investigation.final_score ?? 0}/100 — ${findings.length} finding${findings.length !== 1 ? "s" : ""}`
              : `All sources failed: ${investigation.failed_sources.map((f) => f.source).join(", ")}`,
            status: investigation.status === "COMPLETED" ? "completed" : "failed",
          },
        ]
      : []),
  ];

  return (
    <div className="panel" style={{ padding: "1.25rem" }}>
      <div
        style={{
          fontFamily: "var(--font-display)",
          fontSize: "1rem",
          fontWeight: 500,
          marginBottom: "1.25rem",
          color: "var(--text-primary)",
        }}
      >
        Investigation Timeline
      </div>

      <div className="timeline-spine">
        {steps.map((step, idx) => (
          <div
            key={idx}
            className={`timeline-step ${step.status}`}
            style={{ marginBottom: "1rem" }}
          >
            <div style={{ display: "flex", alignItems: "flex-start", gap: "8px" }}>
              <span className="mono text-tertiary" style={{ fontSize: "0.6875rem", flexShrink: 0, marginTop: "2px", minWidth: "56px" }}>
                {step.time}
              </span>
              <div>
                <div style={{ fontSize: "0.875rem", color: "var(--text-primary)", fontWeight: 500 }}>
                  {step.label}
                </div>
                <div className="mono" style={{ fontSize: "0.75rem", color: "var(--text-tertiary)", marginTop: "2px" }}>
                  {step.detail}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {metrics && (
        <div
          style={{
            marginTop: "1.25rem",
            paddingTop: "1rem",
            borderTop: "var(--border)",
          }}
        >
          <div
            style={{
              fontFamily: "var(--font-mono)",
              fontSize: "0.625rem",
              textTransform: "uppercase",
              letterSpacing: "0.1em",
              color: "var(--text-tertiary)",
              marginBottom: "0.75rem",
            }}
          >
            Investigation Metrics
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
            {[
              { label: "Artifacts", value: metrics.artifacts_fetched },
              { label: "Evidence", value: metrics.evidence_extracted },
              { label: "Findings", value: metrics.findings_generated },
              { label: "Failed Sources", value: metrics.failed_sources_count },
              { label: "Execution Time", value: `${(metrics.execution_time_ms / 1000).toFixed(1)}s` },
            ].map(({ label, value }) => (
              <div key={label} style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                <span className="mono" style={{ fontSize: "0.75rem", color: "var(--text-tertiary)" }}>
                  {label}
                </span>
                <span className="mono" style={{ fontSize: "0.875rem", color: "var(--text-primary)" }}>
                  {value}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default function DemoInvestigationDetailPage() {
  const params = useParams();
  const id = params.id as string;
  const [data, setData] = useState<InvestigationDetail | null>(null);
  const [error, setError] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    const res = await fetch(`/api/demo/${id}`);
    if (!res.ok) {
      setError("Investigation not found or is not public");
      return;
    }
    const d = await res.json() as InvestigationDetail;
    setData(d);
  }, [id]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    fetchData();
  }, [fetchData]);

  if (error) return (
    <div style={{ padding: "2rem 2.5rem", color: "var(--accent-severe)" }}>{error}</div>
  );

  if (!data) {
    return (
      <div style={{ padding: "2rem 2.5rem" }}>
        <div className="redacted-line" style={{ width: "300px", height: "24px", marginBottom: "1rem" }} />
        <div className="redacted-block" style={{ width: "100%", height: "200px" }} />
      </div>
    );
  }

  const inProgress = !["COMPLETED", "FAILED"].includes(data.status);
  const uniqueSources = [...new Set(data.artifacts.map((a) => a.source))];

  return (
    <>
      <style>{`
        .detail-page { padding: 1.5rem 2rem; max-width: 1200px; }

        .detail-header {
          margin-bottom: 1.5rem;
          padding-bottom: 1.25rem;
          border-bottom: var(--border);
        }

        .detail-case-number { margin-bottom: 4px; }

        .detail-target {
          font-family: var(--font-display);
          font-size: 1.5rem;
          font-weight: 500;
          color: var(--text-primary);
          margin-bottom: 0.5rem;
          word-break: break-all;
        }

        .detail-meta {
          display: flex;
          align-items: center;
          gap: 1rem;
          flex-wrap: wrap;
        }

        .detail-layout {
          display: grid;
          grid-template-columns: 1fr 280px;
          gap: 1.5rem;
          align-items: start;
        }

        .detail-main { min-width: 0; }

        .detail-sidebar { }

        .source-status-bar {
          display: flex;
          align-items: center;
          gap: 1rem;
          padding: 0.75rem 1rem;
          background: var(--bg-surface);
          border: var(--border);
          border-radius: var(--radius-sm);
          margin-bottom: 1.5rem;
          flex-wrap: wrap;
        }

        .source-status-label {
          font-family: var(--font-mono);
          font-size: 0.6875rem;
          text-transform: uppercase;
          letter-spacing: 0.1em;
          color: var(--text-tertiary);
          flex-shrink: 0;
        }

        .source-status-list {
          display: flex;
          gap: 1rem;
          flex-wrap: wrap;
        }

        .source-status-item {
          font-family: var(--font-mono);
          font-size: 0.75rem;
          display: flex;
          align-items: center;
          gap: 4px;
        }

        .status-pill {
          font-family: var(--font-mono);
          font-size: 0.6875rem;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          padding: 2px 8px;
          border-radius: 2px;
          border: 1px solid;
        }

        .status-in-progress {
          color: var(--accent-open);
          border-color: var(--accent-open);
          background: color-mix(in srgb, var(--accent-open) 8%, transparent);
        }

        .status-completed {
          color: var(--accent-confirmed);
          border-color: var(--accent-confirmed);
          background: color-mix(in srgb, var(--accent-confirmed) 8%, transparent);
        }

        .status-failed {
          color: var(--accent-severe);
          border-color: var(--accent-severe);
          background: color-mix(in srgb, var(--accent-severe) 8%, transparent);
        }

        .section-title {
          font-family: var(--font-display);
          font-size: 1rem;
          font-weight: 500;
          color: var(--text-primary);
          margin-bottom: 0.75rem;
        }

        .findings-list {
          display: flex;
          flex-direction: column;
          gap: 6px;
          margin-bottom: 1.5rem;
        }

        .finding-card {
          padding: 0;
          overflow: hidden;
        }

        .finding-card-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 12px 14px;
          cursor: pointer;
          gap: 12px;
        }

        .finding-card-header:hover { background: var(--bg-surface-2); }

        .finding-card-left {
          display: flex;
          align-items: center;
          gap: 10px;
          min-width: 0;
          flex: 1;
        }

        .finding-claim {
          font-size: 0.9375rem;
          color: var(--text-primary);
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }

        .finding-card-right {
          display: flex;
          align-items: center;
          gap: 10px;
          flex-shrink: 0;
        }

        .analyzer-badge {
          font-family: var(--font-mono);
          font-size: 0.5625rem;
          font-weight: 600;
          letter-spacing: 0.08em;
          padding: 2px 6px;
          background: var(--bg-surface-2);
          border: 1px solid var(--bg-border);
          border-radius: 2px;
          color: var(--text-tertiary);
          flex-shrink: 0;
        }

        .evidence-panel-body {
          padding: 14px;
          border-top: var(--border);
          background: var(--bg-base);
        }

        .ep-meta-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 0.75rem;
          flex-wrap: wrap;
          gap: 8px;
        }

        .ep-reasoning {
          font-size: 0.875rem;
          color: var(--text-secondary);
          line-height: 1.6;
          margin-bottom: 1rem;
          padding: 10px 12px;
          background: var(--bg-surface);
          border-left: 2px solid var(--accent-confirmed);
          border-radius: 0 var(--radius-sm) var(--radius-sm) 0;
        }

        .ep-section-label {
          font-family: var(--font-mono);
          font-size: 0.625rem;
          text-transform: uppercase;
          letter-spacing: 0.1em;
          color: var(--text-tertiary);
          margin-bottom: 6px;
        }

        .ep-evidence-list {
          display: flex;
          flex-direction: column;
          gap: 4px;
        }

        .ep-evidence-row {
          display: flex;
          gap: 12px;
          align-items: baseline;
          padding: 4px 8px;
          background: var(--bg-surface);
          border-radius: var(--radius-sm);
        }

        .ep-evidence-row span:first-child { flex-shrink: 0; min-width: 140px; }

        .raw-artifact-view {
          margin-top: 12px;
          padding: 12px;
          background: var(--bg-base);
          border: var(--border);
          border-radius: var(--radius-sm);
          font-family: var(--font-mono);
          font-size: 0.75rem;
          color: var(--text-secondary);
          overflow-x: auto;
          max-height: 400px;
          overflow-y: auto;
          white-space: pre;
        }

        .score-breakdown-list {
          display: flex;
          flex-direction: column;
          gap: 4px;
        }

        .score-breakdown-row {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 6px 8px;
          border-radius: var(--radius-sm);
        }

        .score-breakdown-row:hover { background: var(--bg-surface-2); }

        .score-breakdown-total {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 8px;
          border-top: var(--border);
          margin-top: 6px;
          font-size: 1.125rem;
          font-family: var(--font-mono);
          font-weight: 600;
        }

        .notes-section { margin-top: 1.5rem; }

        .note-item {
          padding: 10px 14px;
          background: var(--bg-surface);
          border: var(--border);
          border-radius: var(--radius-sm);
          margin-bottom: 6px;
        }

        .note-content {
          font-size: 0.875rem;
          color: var(--text-primary);
          line-height: 1.6;
          white-space: pre-wrap;
        }

        .note-time {
          font-family: var(--font-mono);
          font-size: 0.6875rem;
          color: var(--text-tertiary);
          margin-top: 6px;
        }

        .tags-row {
          display: flex;
          flex-wrap: wrap;
          gap: 6px;
          align-items: center;
        }

        .tag-pill {
          font-family: var(--font-mono);
          font-size: 0.6875rem;
          padding: 2px 10px;
          border: 1px solid var(--bg-border);
          border-radius: 100px;
          color: var(--text-secondary);
          display: flex;
          align-items: center;
          gap: 6px;
        }

        .tag-remove {
          background: none;
          border: none;
          color: var(--text-tertiary);
          cursor: pointer;
          font-size: 0.75rem;
          padding: 0;
          line-height: 1;
        }

        .tag-remove:hover { color: var(--accent-severe); }

        .prior-inv-banner {
          padding: 10px 14px;
          background: color-mix(in srgb, var(--accent-open) 8%, var(--bg-surface));
          border: 1px solid var(--accent-open);
          border-radius: var(--radius-sm);
          margin-bottom: 1.5rem;
          font-size: 0.875rem;
          color: var(--text-secondary);
        }
      `}</style>

      <div className="detail-page">
        <div className="detail-header">
          <div className="detail-case-number">
            <span className="case-number-prominent">{data.case_number}</span>
            {" — "}
            <span
              className={`status-pill ${
                inProgress ? "status-in-progress" : data.status === "COMPLETED" ? "status-completed" : "status-failed"
              }`}
            >
              {STATUS_LABELS[data.status]}
            </span>
          </div>
          <div className="detail-target">{data.target}</div>
          <div className="detail-meta">
            <span className="mono" style={{ fontSize: "0.75rem", color: "var(--text-tertiary)" }}>
              {data.target_type}
            </span>
            <span style={{ fontSize: "0.75rem", color: "var(--text-tertiary)" }}>
              Opened {new Date(data.created_at).toLocaleString()}
            </span>
            {data.tags.map((tag) => (
              <span key={(tag as { id: string }).id} className="tag-pill">
                {(tag as { name: string }).name}
              </span>
            ))}
          </div>
        </div>

        {/* IOC History banner */}
        {data.prior_investigations && data.prior_investigations.length > 0 && (
          <div className="prior-inv-banner">
            Previously seen {data.prior_investigations.length} time{data.prior_investigations.length !== 1 ? "s" : ""}.{" "}
            Last investigation: {data.prior_investigations[0].case_number} —
            Score: {data.prior_investigations[0].final_score ?? "—"} —{" "}
            {new Date(data.prior_investigations[0].created_at).toLocaleDateString()}
          </div>
        )}

        {/* Source status bar */}
        {uniqueSources.length > 0 && (
          <SourceStatusBar
            failedSources={data.failed_sources}
            sources={uniqueSources}
          />
        )}



        {/* In-progress redaction */}
        {inProgress && (
          <div style={{ marginBottom: "1.5rem" }}>
            <div className="redacted-block" style={{ height: "120px", borderRadius: "var(--radius-sm)" }} />
            <div style={{ marginTop: "8px", fontSize: "0.8125rem", color: "var(--accent-open)", fontFamily: "var(--font-mono)" }}>
              {STATUS_LABELS[data.status]}
            </div>
          </div>
        )}

        <div className="detail-layout">
          <div className="detail-main">
            {/* Findings */}
            {data.findings.length > 0 && (
              <div style={{ marginBottom: "1.5rem" }}>
                <div className="section-title">Findings ({data.findings.length})</div>
                <div className="findings-list">
                  {data.findings.map((f) => (
                    <FindingCard key={f.id} finding={f} artifacts={data.artifacts} />
                  ))}
                </div>
              </div>
            )}

            {/* Score breakdown removed from here, now in sidebar */}

            {/* Timeline */}
            <div style={{ marginBottom: "1.5rem" }}>
              <InvestigationTimeline investigation={data} />
            </div>

            {/* Analyst Notes */}
            <div className="notes-section">
              <div className="section-title">Analyst Notes</div>
              {data.notes.map((note) => (
                <div key={note.id} className="note-item">
                  <div className="note-content">{note.content}</div>
                  <div className="note-time">
                    {new Date(note.created_at).toLocaleString()}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Sticky sidebar */}
          <div className="detail-sidebar" style={{ position: "sticky", top: "1.5rem" }}>
            <EvidenceLedger investigation={data} />
          </div>
        </div>
      </div>
    </>
  );
}
