"use client";

import { useEffect, useState, useCallback } from "react";
import { useParams } from "next/navigation";
import { confidenceLabel } from "@/lib/pipeline/confidence";
import { MITRE_MAPPINGS } from "@/lib/attack/mitreMapping";
import type { InvestigationDetail, Finding, Evidence, Artifact } from "@/lib/pipeline/types";
import RadarChart from "@/components/RadarChart";

const ANALYZER_BADGES: Record<string, string> = {
  VirusTotalAnalyzer: "VT",
  AbuseIPDBAnalyzer: "ABUSE",
  DomainAgeAnalyzer: "WHOIS",
  EntropyAnalyzer: "ENT",
  ASNReputationAnalyzer: "ASN",
  HomographAnalyzer: "HOM",
  EmailAuthAnalyzer: "HDR",
  FingerprintAnalyzer: "FP",
  CVEPriorityAnalyzer: "CVE",
};

const STATUS_LABELS: Record<string, string> = {
  CREATED: "Created",
  FETCHING_ARTIFACTS: "Fetching sources…",
  EXTRACTING_EVIDENCE: "Extracting evidence…",
  RUNNING_ANALYZERS: "Running analyzers…",
  SCORING: "Computing score…",
  COMPLETED: "Completed",
  FAILED: "Failed",
};

function ScoreColor(score: number): string {
  if (score >= 75) return "var(--severity-critical)";
  if (score >= 50) return "var(--severity-high)";
  if (score >= 25) return "var(--severity-medium)";
  return "var(--severity-low)";
}

function StampBadge({ status, onClick, interactive }: { status: string; onClick?: (e: React.MouseEvent) => void; interactive?: boolean }) {
  const [animated, setAnimated] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setAnimated(true), 100);
    return () => clearTimeout(t);
  }, []);

  const cls = `finding-status status-${status} ${animated ? "stamp-animate" : ""} ${interactive ? "interactive-badge" : ""}`;
  return (
    <span className={cls} onClick={onClick} style={interactive ? { cursor: "pointer" } : {}}>
      {status.replace("_", " ")}
      {interactive && <span style={{ marginLeft: "4px", fontSize: "0.6rem" }}>▼</span>}
    </span>
  );
}

function EvidencePanelContent({
  finding,
  artifacts,
}: {
  finding: Finding & { evidence?: Evidence[] };
  artifacts: Artifact[];
}) {
  const [showRaw, setShowRaw] = useState(false);

  const evidenceList = finding.evidence ?? [];

  // Find the artifact for the first evidence item
  const firstEvidence = evidenceList[0];
  const relatedArtifact = firstEvidence
    ? artifacts.find((a) =>
        evidenceList.some(
          (ev: Evidence) => (ev as Evidence & { artifact_id: string }).artifact_id === a.id
        )
      )
    : null;

  return (
    <div className="evidence-panel-body">
      <div className="ep-meta-row">
        <span className="text-secondary" style={{ fontSize: "0.8125rem" }}>
          Generated by{" "}
          <span className="mono" style={{ color: "var(--accent-open)" }}>
            {finding.generated_by} v{finding.analyzer_version}
          </span>
        </span>
        <span className="text-tertiary" style={{ fontSize: "0.75rem" }}>
          Score contribution:{" "}
          <span className="mono" style={{ color: ScoreColor(finding.confidence_score) }}>
            +{finding.score_contribution}
          </span>
        </span>
      </div>

      {finding.reasoning && (
        <p className="ep-reasoning">{finding.reasoning}</p>
      )}

      {evidenceList.length > 0 && (
        <div className="ep-evidence-list">
          <div className="ep-section-label">Evidence</div>
          {evidenceList.map((ev: Evidence) => (
            <div key={ev.id} className="ep-evidence-row">
              <span className="mono text-tertiary" style={{ fontSize: "0.75rem" }}>
                {ev.fact_type}
              </span>
              <span className="mono" style={{ fontSize: "0.8125rem", color: "var(--text-primary)" }}>
                {typeof ev.fact_value === "object"
                  ? JSON.stringify(ev.fact_value)
                  : String(ev.fact_value)}
              </span>
            </div>
          ))}
        </div>
      )}

      {relatedArtifact && (
        <div style={{ marginTop: "1rem" }}>
          <button
            className="btn btn-secondary"
            style={{ fontSize: "0.8125rem", padding: "6px 12px" }}
            onClick={() => setShowRaw(!showRaw)}
            id={`raw-artifact-toggle-${finding.id}`}
          >
            {showRaw ? "Hide Raw Artifact" : "View Raw Artifact →"}
          </button>
          {showRaw && (
            <pre className="raw-artifact-view">
              {JSON.stringify(relatedArtifact.raw_response, null, 2)}
            </pre>
          )}
        </div>
      )}
      {(finding as any).disposition_note && (
        <div style={{ marginTop: "12px", padding: "8px", background: "var(--bg-surface)", borderLeft: "2px solid var(--accent-open)", fontSize: "0.8125rem", borderRadius: "0 4px 4px 0" }}>
          <div style={{ color: "var(--text-tertiary)", fontSize: "0.6875rem", textTransform: "uppercase", marginBottom: "4px", fontFamily: "var(--font-mono)" }}>Analyst Disposition Note</div>
          <div style={{ color: "var(--text-primary)" }}>{(finding as any).disposition_note}</div>
        </div>
      )}
    </div>
  );
}

function FindingCard({
  finding,
  artifacts,
  isCompleted,
  onUpdateDisposition,
}: {
  finding: Finding & { evidence?: Evidence[], disposition_note?: string | null };
  artifacts: Artifact[];
  isCompleted?: boolean;
  onUpdateDisposition?: (status: string, note?: string) => Promise<any>;
}) {
  const [open, setOpen] = useState(false);
  const [showDispositionForm, setShowDispositionForm] = useState(false);
  const [dispositionStatus, setDispositionStatus] = useState("CONFIRMED");
  const [dispositionNote, setDispositionNote] = useState("");
  const [savingDisposition, setSavingDisposition] = useState(false);

  const badge = ANALYZER_BADGES[finding.generated_by] ?? finding.generated_by.slice(0, 4).toUpperCase();
  const conf = confidenceLabel(finding.confidence_score);

  const handleDispositionClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (isCompleted && onUpdateDisposition) {
      setShowDispositionForm(!showDispositionForm);
    }
  };

  const submitDisposition = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!onUpdateDisposition) return;
    setSavingDisposition(true);
    await onUpdateDisposition(dispositionStatus, dispositionNote);
    setSavingDisposition(false);
    setShowDispositionForm(false);
    setDispositionNote("");
  };

  return (
    <div className="finding-card evidence-tag">
      <div
        className="finding-card-header"
        onClick={() => setOpen(!open)}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => e.key === "Enter" && setOpen(!open)}
        id={`finding-${finding.id}`}
        aria-expanded={open}
      >
        <div className="finding-card-left">
          <span
            className="analyzer-badge"
            title={finding.generated_by}
            aria-label={finding.generated_by}
          >
            {badge}
          </span>
          <span className="finding-claim">{finding.claim}</span>
        </div>
        <div className="finding-card-right">
          {finding.attack_techniques?.map((t) => (
            <a
              key={t}
              href={MITRE_MAPPINGS[t]?.url ?? `https://attack.mitre.org/techniques/${t.split('.')[0]}/`}
              target="_blank"
              rel="noreferrer"
              className="severity-badge severity-INFO"
              style={{ textDecoration: "none" }}
              onClick={(e) => e.stopPropagation()}
              title={MITRE_MAPPINGS[t]?.techniqueName}
            >
              {t}
            </a>
          ))}
          <span className={`severity-badge severity-${finding.severity}`}>
            {finding.severity}
          </span>
          <span
            className="mono"
            style={{ fontSize: "0.75rem", color: "var(--text-tertiary)" }}
          >
            {finding.confidence_score}
            <span style={{ marginLeft: "2px", opacity: 0.6 }}>({conf})</span>
          </span>
          <StampBadge 
            status={finding.status} 
            onClick={handleDispositionClick} 
            interactive={isCompleted && !!onUpdateDisposition} 
          />
          <span style={{ color: "var(--text-tertiary)", fontSize: "0.875rem" }}>
            {open ? "▲" : "▼"}
          </span>
        </div>
      </div>

      {showDispositionForm && (
        <div style={{ padding: "12px 14px", background: "var(--bg-surface-2)", borderTop: "var(--border)" }} onClick={(e) => e.stopPropagation()}>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: "0.6875rem", textTransform: "uppercase", marginBottom: "8px", color: "var(--text-secondary)" }}>Update Disposition</div>
          <form onSubmit={submitDisposition}>
            <select 
              value={dispositionStatus}
              onChange={(e) => setDispositionStatus(e.target.value)}
              className="input"
              style={{ padding: "4px 8px", fontSize: "0.75rem", marginBottom: "8px", width: "100%", maxWidth: "200px", display: "block" }}
            >
              <option value="CONFIRMED">Confirmed</option>
              <option value="CLEARED">Cleared</option>
              <option value="UNDER_REVIEW">Under Review</option>
              <option value="FLAGGED">Flagged</option>
            </select>
            {["CONFIRMED", "CLEARED"].includes(dispositionStatus) && (
              <textarea
                value={dispositionNote}
                onChange={(e) => setDispositionNote(e.target.value)}
                className="input"
                placeholder="Reasoning (min 10 chars)..."
                rows={2}
                style={{ fontSize: "0.75rem", marginBottom: "8px", width: "100%" }}
                required
                minLength={10}
              />
            )}
            <div style={{ display: "flex", gap: "8px" }}>
              <button type="submit" className="btn btn-secondary" disabled={savingDisposition || (["CONFIRMED", "CLEARED"].includes(dispositionStatus) && dispositionNote.length < 10)} style={{ fontSize: "0.75rem", padding: "4px 8px" }}>
                {savingDisposition ? "Saving..." : "Save"}
              </button>
              <button type="button" className="btn btn-secondary" onClick={() => setShowDispositionForm(false)} style={{ fontSize: "0.75rem", padding: "4px 8px" }}>
                Cancel
              </button>
            </div>
          </form>
        </div>
      )}

      {open && (
        <EvidencePanelContent finding={finding} artifacts={artifacts} />
      )}
    </div>
  );
}

function SourceStatusBar({
  failedSources = [],
  sources,
}: {
  failedSources?: Array<{ source: string; reason: string }>;
  sources: string[];
}) {
  const failedSet = new Set(failedSources.map((f) => f.source));
  const failedMap = Object.fromEntries(failedSources.map((f) => [f.source, f.reason]));

  return (
    <div className="source-status-bar">
      <span className="source-status-label">Sources</span>
      <div className="source-status-list">
        {sources.map((src) => {
          const failed = failedSet.has(src);
          return (
            <span
              key={src}
              className={`source-status-item ${failed ? "source-fail" : "source-ok"}`}
              title={failed ? failedMap[src] : "Success"}
            >
              {failed ? "⚠" : "✓"} {src}
            </span>
          );
        })}
      </div>
    </div>
  );
}

function EvidenceLedger({
  investigation,
}: {
  investigation: InvestigationDetail;
}) {
  const { case_number, target, findings, final_score } = investigation;
  const sorted = [...findings].sort((a, b) => b.score_contribution - a.score_contribution);

  return (
    <div className="panel" style={{
      fontFamily: "var(--font-mono)",
      padding: "1rem",
      fontSize: "0.8125rem",
      lineHeight: "1.5",
      color: "var(--text-primary)"
    }}>
      {/* Header */}
      <div style={{ borderBottom: "1px dashed var(--text-tertiary)", paddingBottom: "1rem", marginBottom: "1rem" }}>
        <div style={{ fontWeight: 600, letterSpacing: "0.05em", marginBottom: "0.5rem" }}>THREAT SCORE LEDGER</div>
        <div style={{ display: "flex", justifyContent: "space-between", color: "var(--text-secondary)" }}>
          <span>CASE: {case_number}</span>
          <span>TARGET: {target}</span>
        </div>
      </div>
      
      {/* Radar Chart */}
      {findings.length > 0 && (
        <div style={{ marginBottom: "1.5rem", paddingBottom: "1rem", borderBottom: "1px dashed var(--text-tertiary)" }}>
          <RadarChart findings={findings} />
        </div>
      )}
      
      {/* Table Header */}
      <div style={{ display: "flex", justifyContent: "space-between", color: "var(--text-secondary)", marginBottom: "0.5rem" }}>
        <span>CONTRIBUTING FACTOR</span>
        <span>IMPACT</span>
      </div>
      <div style={{ borderBottom: "1px dashed var(--text-tertiary)", marginBottom: "0.5rem" }}></div>
      
      {/* Items */}
      <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem", marginBottom: "1rem" }}>
        {sorted.map(f => (
          <div key={f.id} style={{ display: "flex", justifyContent: "space-between" }}>
            <span style={{ paddingRight: "1rem", wordBreak: "break-word" }}>{f.claim}</span>
            <span style={{ 
              color: f.score_contribution > 0 ? ScoreColor(f.confidence_score) : "var(--text-tertiary)",
              whiteSpace: "nowrap",
              textAlign: "right"
            }}>
              +{f.score_contribution}
            </span>
          </div>
        ))}
      </div>
      
      {/* Footer */}
      <div style={{ borderTop: "1px dashed var(--text-tertiary)", paddingTop: "1rem" }}>
        <div style={{ display: "flex", justifyContent: "space-between", fontWeight: 600 }}>
          <span>COMPOSITE SCORE SUMMARY</span>
          <span style={{ color: final_score !== null ? ScoreColor(final_score) : "var(--text-primary)" }}>
            SCORE: {final_score ?? "—"}
          </span>
        </div>
      </div>
    </div>
  );
}

function InvestigationTimeline({
  investigation,
}: {
  investigation: InvestigationDetail;
}) {
  const artifacts = investigation.artifacts;
  const findings = investigation.findings;
  const metrics = investigation.metrics;

  const formatTime = (d?: string | null) =>
    d ? new Date(d).toLocaleTimeString("en-US", { hour12: false, hour: "2-digit", minute: "2-digit", second: "2-digit" }) : "Unknown";

  const steps = [
    {
      time: formatTime(investigation.created_at),
      label: "IOC submitted",
      detail: `Target: ${investigation.target} (${investigation.target_type})`,
      status: "completed",
    },
    ...artifacts.map((art) => {
      const artFindings = findings.filter((f) =>
        f.evidence?.some((ev: Evidence) => (ev as Evidence & { artifact_id?: string }).artifact_id === art.id)
      );
      const artEvidence = (investigation.all_evidence || []).filter(
        (ev: Evidence) => ev.artifact_id === art.id
      );
      return {
        time: formatTime(art.fetched_at || ((art as unknown) as Record<string, unknown>).created_at as string),
        label: `${art.source} artifact ${art.is_reused ? "(cached)" : "fetched"}`,
        detail: `${artEvidence.length} evidence fact${artEvidence.length !== 1 ? "s" : ""} extracted${artFindings.length > 0 ? `, ${artFindings.length} finding${artFindings.length !== 1 ? "s" : ""}` : ""}`,
        status: "completed",
      };
    }),
    ...(investigation.status === "COMPLETED" || investigation.status === "FAILED"
      ? [
          {
            time: investigation.completed_at
              ? formatTime(investigation.completed_at)
              : "",
            label: investigation.status === "COMPLETED"
              ? `Score computed under Scoring Profile v${investigation.scoring_profile_version ?? "1.0"}`
              : "Investigation failed",
            detail: investigation.status === "COMPLETED"
              ? `Final verdict: ${investigation.final_score ?? 0}/100 — ${findings.length} finding${findings.length !== 1 ? "s" : ""}`
              : `All sources failed: ${investigation.failed_sources.map((f) => f.source).join(", ")}`,
            status: investigation.status === "COMPLETED" ? "completed" : "failed",
          },
        ]
      : []),
  ];

  return (
    <div className="panel" style={{ padding: "1.25rem" }}>
      <div
        style={{
          fontFamily: "var(--font-display)",
          fontSize: "1rem",
          fontWeight: 500,
          marginBottom: "1.25rem",
          color: "var(--text-primary)",
        }}
      >
        Investigation Timeline
      </div>

      <div className="timeline-spine">
        {steps.map((step, idx) => (
          <div
            key={idx}
            className={`timeline-step ${step.status}`}
            style={{ marginBottom: "1rem" }}
          >
            <div style={{ display: "flex", alignItems: "flex-start", gap: "8px" }}>
              <span className="mono text-tertiary" style={{ fontSize: "0.6875rem", flexShrink: 0, marginTop: "2px", minWidth: "56px" }}>
                {step.time}
              </span>
              <div>
                <div style={{ fontSize: "0.875rem", color: "var(--text-primary)", fontWeight: 500 }}>
                  {step.label}
                </div>
                <div className="mono" style={{ fontSize: "0.75rem", color: "var(--text-tertiary)", marginTop: "2px" }}>
                  {step.detail}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {metrics && (
        <div
          style={{
            marginTop: "1.25rem",
            paddingTop: "1rem",
            borderTop: "var(--border)",
          }}
        >
          <div
            style={{
              fontFamily: "var(--font-mono)",
              fontSize: "0.625rem",
              textTransform: "uppercase",
              letterSpacing: "0.1em",
              color: "var(--text-tertiary)",
              marginBottom: "0.75rem",
            }}
          >
            Investigation Metrics
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
            {[
              { label: "Artifacts", value: metrics.artifacts_fetched },
              { label: "Evidence", value: metrics.evidence_extracted },
              { label: "Findings", value: metrics.findings_generated },
              { label: "Failed Sources", value: metrics.failed_sources_count },
              { label: "Execution Time", value: `${(metrics.execution_time_ms / 1000).toFixed(1)}s` },
            ].map(({ label, value }) => (
              <div key={label} style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                <span className="mono" style={{ fontSize: "0.75rem", color: "var(--text-tertiary)" }}>
                  {label}
                </span>
                <span className="mono" style={{ fontSize: "0.875rem", color: "var(--text-primary)" }}>
                  {value}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default function InvestigationDetailPage() {
  const params = useParams();
  const id = params.id as string;
  const [data, setData] = useState<InvestigationDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [newNote, setNewNote] = useState("");
  const [newTag, setNewTag] = useState("");
  const [savingNote, setSavingNote] = useState(false);

  const fetchData = useCallback(async () => {
    const res = await fetch(`/api/investigations/${id}`);
    if (!res.ok) {
      setError("Investigation not found");
      return;
    }
    const d = await res.json() as InvestigationDetail;
    setData(d);
  }, [id]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    fetchData();
  }, [fetchData]);

  // Poll while in-progress
  useEffect(() => {
    if (!data) return;
    const inProgress = !["COMPLETED", "FAILED"].includes(data.status);
    if (!inProgress) return;

    let active = true;
    const interval = setInterval(async () => {
      try {
        const res = await fetch(`/api/investigations/${id}`);
        if (!res.ok) return;
        const d = await res.json() as InvestigationDetail;
        if (active) {
          setData(d);
        }
      } catch (err) {
        console.error("Polling error:", err);
      }
    }, 2000);

    return () => {
      active = false;
      clearInterval(interval);
    };
  }, [data?.status, id]);

  const handleAddNote = async () => {
    if (!newNote.trim()) return;
    setSavingNote(true);
    await fetch(`/api/investigations/${id}/notes`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ content: newNote }),
    });
    setNewNote("");
    setSavingNote(false);
    fetchData();
  };

  const handleAddTag = async () => {
    if (!newTag.trim()) return;
    await fetch(`/api/investigations/${id}/tags`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ tagName: newTag }),
    });
    setNewTag("");
    fetchData();
  };

  const handleRemoveTag = async (tagId: string) => {
    await fetch(`/api/investigations/${id}/tags`, {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ tagId }),
    });
    fetchData();
  };

  const handleUpdateDisposition = async (findingId: string, status: string, note?: string) => {
    const res = await fetch(`/api/investigations/${id}/findings/${findingId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status, note }),
    });
    if (res.ok) {
      fetchData();
    }
    return res;
  };

  if (error) return (
    <div style={{ padding: "2rem 2.5rem", color: "var(--accent-severe)" }}>{error}</div>
  );

  if (!data) {
    return (
      <div style={{ padding: "2rem 2.5rem" }}>
        <div className="redacted-line" style={{ width: "300px", height: "24px", marginBottom: "1rem" }} />
        <div className="redacted-block" style={{ width: "100%", height: "200px" }} />
      </div>
    );
  }

  const inProgress = !["COMPLETED", "FAILED"].includes(data.status);
  const uniqueSources = [...new Set(data.artifacts.map((a) => a.source))];

  return (
    <>
      <div className="detail-page">
        <div className="detail-header">
          <div className="detail-case-number">
            <span className="case-number-prominent">{data.case_number}</span>
            {" — "}
            <span
              className={`status-pill ${
                inProgress ? "status-in-progress" : data.status === "COMPLETED" ? "status-completed" : "status-failed"
              }`}
            >
              {STATUS_LABELS[data.status]}
            </span>
          </div>
          <div className="detail-target">{data.target}</div>
          <div className="detail-meta">
            <span className="mono" style={{ fontSize: "0.75rem", color: "var(--text-tertiary)" }}>
              {data.target_type}
            </span>
            <span style={{ fontSize: "0.75rem", color: "var(--text-tertiary)" }}>
              Opened {new Date(data.created_at).toLocaleString()}
            </span>
            {data.tags.map((tag) => (
              <span key={(tag as { id: string }).id} className="tag-pill">
                {(tag as { name: string }).name}
                <button
                  className="tag-remove"
                  onClick={() => handleRemoveTag((tag as { id: string }).id)}
                  aria-label={`Remove tag ${(tag as { name: string }).name}`}
                >
                  ×
                </button>
              </span>
            ))}
            <form
              onSubmit={(e) => { e.preventDefault(); handleAddTag(); }}
              style={{ display: "flex", gap: "4px" }}
            >
              <input
                className="input"
                value={newTag}
                onChange={(e) => setNewTag(e.target.value)}
                placeholder="Add tag…"
                style={{ width: "120px", padding: "3px 8px", fontSize: "0.75rem" }}
                id="add-tag-input"
              />
            </form>
            {data.status === "COMPLETED" && (
              <a
                href={`/api/investigations/${id}/pdf`}
                target="_blank"
                rel="noreferrer"
                className="btn btn-secondary"
                style={{ fontSize: "0.75rem", padding: "4px 8px", marginLeft: "auto" }}
              >
                Download Forensic Briefing (PDF)
              </a>
            )}
          </div>
        </div>

        {/* IOC History banner */}
        {data.prior_investigations && data.prior_investigations.length > 0 && (
          <div className="prior-inv-banner">
            Previously seen {data.prior_investigations.length} time{data.prior_investigations.length !== 1 ? "s" : ""}.{" "}
            Last investigation: {data.prior_investigations[0].case_number} —
            Score: {data.prior_investigations[0].final_score ?? "—"} —{" "}
            {new Date(data.prior_investigations[0].created_at).toLocaleDateString()}
          </div>
        )}

        {/* Source status bar */}
        {uniqueSources.length > 0 && (
          <SourceStatusBar
            failedSources={data.failed_sources}
            sources={uniqueSources}
          />
        )}



        {/* In-progress redaction */}
        {inProgress && (
          <div style={{ marginBottom: "1.5rem" }}>
            <div className="redacted-block" style={{ height: "120px", borderRadius: "var(--radius-sm)" }} />
            <div style={{ marginTop: "8px", fontSize: "0.8125rem", color: "var(--accent-open)", fontFamily: "var(--font-mono)" }}>
              {STATUS_LABELS[data.status]}
            </div>
          </div>
        )}

        <div className="detail-layout">
          <div className="detail-main">
            {/* Findings */}
            {data.findings.length > 0 && (
              <div style={{ marginBottom: "1.5rem" }}>
                <div className="section-title">Findings ({data.findings.length})</div>
                <div className="findings-list">
                  {data.findings.map((f) => (
                    <FindingCard 
                      key={f.id} 
                      finding={f as any} 
                      artifacts={data.artifacts} 
                      isCompleted={data.status === "COMPLETED"}
                      onUpdateDisposition={(status, note) => handleUpdateDisposition(f.id, status, note)}
                    />
                  ))}
                </div>
              </div>
            )}

            {/* Score breakdown removed from here, now in sidebar */}

            {/* Timeline */}
            <div style={{ marginBottom: "1.5rem" }}>
              <InvestigationTimeline investigation={data} />
            </div>

            {/* Analyst Notes */}
            <div className="notes-section">
              <div className="section-title">Analyst Notes</div>
              <div style={{ display: "flex", gap: "8px", marginBottom: "1rem" }}>
                <textarea
                  className="input"
                  value={newNote}
                  onChange={(e) => setNewNote(e.target.value)}
                  placeholder="Add an analyst note…"
                  rows={3}
                  id="analyst-note-input"
                  style={{ flex: 1 }}
                />
                <button
                  className="btn btn-secondary"
                  onClick={handleAddNote}
                  disabled={savingNote || !newNote.trim()}
                  id="save-note-btn"
                  style={{ alignSelf: "flex-start" }}
                >
                  Save
                </button>
              </div>
              {data.notes.map((note) => (
                <div key={note.id} className="note-item">
                  <div className="note-content">{note.content}</div>
                  <div className="note-time">
                    {new Date(note.created_at).toLocaleString()}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Sticky sidebar */}
          <div className="detail-sidebar" style={{ position: "sticky", top: "1.5rem" }}>
            <EvidenceLedger investigation={data} />
          </div>
        </div>
      </div>
    </>
  );
}
